# ------------------------------------------------------------------------------
# Application |
# ------------------------------------------------------------------------------
application   :
  title       : The name of your application here
  language    : pt-BR
  charset     :
  version     : 1.0.0
  dev_mode    : true
# ------------------------------------------------------------------------------
# Server      |
# ------------------------------------------------------------------------------
server        :
  port        :
  static_dir  : true
# ------------------------------------------------------------------------------
# Connection  |
# ------------------------------------------------------------------------------
connection    :
  driver      : mysql
  host        : localhost
  port        :
  username    : jnex
  password    :
  database    : jnex
  charset     : utf8
  collate     : utf8_unicode_ci
  # MongoDB   |-----------------------------------------------------------------
  mongodb     :
    host      : localhost
    port      :
    username  :
    password  :
    database  :
