#==============================================================================#
application:                                                                   #
#==============================================================================#
  title    : The name of your application here
  version  : 1.0.0
  port     :
  dev_mode : true
#==============================================================================#
location   :                                                                   #
#==============================================================================#
  language : pt-BR
  charset  :
#==============================================================================#
connection :                                                                   #
#==============================================================================#
  driver   : mysql
  host     : localhost
  port     :
  username :
  password :
  database : jnex
  charset  : utf8
  collate  : utf8_unicode_ci
