#=============================================================================#
application:                                                                  #
#=============================================================================#
  title    :
  version  : 1.0.0
  port     :
  dev_mode : true
#=============================================================================#
location   :                                                                  #
#=============================================================================#
  language :
  charset  :
#=============================================================================#
connection :                                                                  #
#=============================================================================#
  driver   : mysql
  host     : localhost
  port     :
  username :
  password :
  database :
  charset  : utf8
  collate  : utf8_unicode_ci
